apiVersion: skaffold/v2beta11
kind: Config

build:
  artifacts:
    - image: bookmark
      context: ./apps/bookmark_server
      docker:
        dockerfile: Dockerfile
        target: builder

    - image: cors
      context: ./apps/cors
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    releases:
      - name: local
        chartPath: ./k8s
        namespace: local
        createNamespace: true
        artifactOverrides:
          bookmarkImage: bookmark
          corsImage: cors
