apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark
  labels:
    app: bookmark
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookmark
  template:
    metadata:
      labels:
        app: bookmark
    spec:
      containers:
        - name: bookmark
          image: {{ $.Values.bookmarkImage }} # 手元でビルドした app コンテナのイメージ名
          imagePullPolicy: IfNotPresent # 先にローカルにimageが存在するかをチェックする
          ports:
            - containerPort: 5000 # appコンテナのlistenポート
          env:
            - name: SERVER_PORT
              value: "5000"
            - name: DB_CONNECTION
              value: mysql:3306
            - name: DB_USER
              value: dev
            - name: DB_PASSWORD
              value: password
            - name: DB_DATABASE
              value: test
            - name: SALT
              value: nim

        - name: cors
          image: {{ $.Values.corsImage }} # 手元でビルドした app コンテナのイメージ名
          imagePullPolicy: IfNotPresent # 先にローカルにimageが存在するかをチェックする
          ports:
            - containerPort: 81
          env:
            - name: ALLOW_ORIGIN
              value: localhost:5000
            - name: LISTEN_PORT
              value: "81"
            - name: TARGET_PORT
              value: "5000"
